background_opacity 0.75
cursor_trail 3

allow_remote_control yes
font_family      Hurmit Nerd Font Mono
#font_family Terminess Nerd Font Mono 
#bold_font Terminess Nerd Font Mono Bold
#jitalic_font Terminess Nerd Font Mono Italic
font_size 16

#modify_font baseline -2px 
#

map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
map ctrl+shift+c send_text all \x03
map ctrl+shift+v paste_from_selection
